# Generated by Django 5.0.6 on 2024-08-25 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_flightbooking_price_flightschedule_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='firstname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='lastname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.userregistration'),
        ),
    ]
