# Generated by Django 5.0.6 on 2024-08-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_passenger_email_passenger_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
