# Generated by Django 4.2.9 on 2024-10-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_adminregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregistration',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
